// flow-typed signature: 76ace25140874980a6ac22dd43ef4fa8
// flow-typed version: <<STUB>>/@eric.dahlseng/linter-configuration_v^0.1.2/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@eric.dahlseng/linter-configuration'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@eric.dahlseng/linter-configuration' {
  declare module.exports: any;
}
